name: flutter_playground
description: My Flutter Playground

version: 1.0.0+1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  shared_preferences: ^0.5.3+5
  cached_network_image: ^1.1.2+1
  flutter_cache_manager: ^1.1.3
  provider: ^3.1.0+1
  get_it: ^3.0.3
  fluttertoast: ^3.1.3
  share: ^0.6.2+4
  dio: 2.1.16
  alice: ^0.0.13
  flutter_local_notifications: ^0.8.2
  flutter_screenutil: 0.5.3
  path_provider: ^1.4.0
  path: ^1.6.4
  firebase_core: ^0.4.0+9
  firebase_analytics: ^5.0.2
  firebase_crashlytics: ^0.1.0+3
  cloud_firestore: ^0.12.9+5
  location: ^2.3.5
  logger: ^0.7.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
